Repository 42-AI/SentimentalBB, pull requests merged in 2022-03, with the labels that each got.

#3 docs (contributor) add of mdavid as contributor
  README.md
Labels: documentation

#11 5 docs (contrib) add athirion as contributor
  README.md
Labels: documentation

#9 Update README.md
  README.md
Labels: documentation

#12 Rebase
  README.md
Labels: documentation

#21 13 feat(data) download a tweet mentioning emmanuel macron with a script
  README.md
  notebooks/first_tweet.ipynb
  requirements.txt
  src/__main__.py
  src/data/main.py
  src/data/make_dataset/__init__.py
  src/data/make_dataset/aclImdb.py
  src/data/make_dataset/macron.py
Labels: feature

#29 20 feat (model) 1 fit and predict on the training dataset
  .42AI/pre-commit.git
  .github/workflows/tests.yaml
  .gitignore
  notebooks/02-at-Preprocess-and-fit-model-aclImdb.ipynb
  notebooks/first_tweet.ipynb
  requirements.txt
  scripts/setup_test_aclImdb.sh
  src/__init__.py
  src/__main__.py
  src/features/build_features.py
  src/models/__init__.py
  src/models/main.py
  src/models/random/predict_model_random.py
  src/models/sklearn/Naive_Bayes.py
  src/models/train_model.py
  src/tests/test_aclImdb.py
Labels: feature

#45 35 data allocine use allocine dataset
  .github/workflows/cicd.yaml
  poetry.lock
  pyproject.toml
  scripts/setup_test_allocine_naive_bayes.sh
  src/__main__.py
  src/data/main.py
  src/data/make_dataset/allocine.py
Labels: feature

#44 Docs (github pages) : update index page
  docs/index.md
Labels: documentation

#50 setup + doc (poetry): Specify how to install poetry tools into the sg…
  Setup.md
Labels: documentation

#63 docs (issue templates): testing with project and status item
  .github/ISSUE_TEMPLATE/42AI_issue.md
  .github/workflows/issue_triage.yaml
Labels: fixme

#67 doc(report) redaction of the skeleton for the global report and repor…
  reports/.template_report.md
  reports/reports.md
Labels: documentation

#69 Revert "docs (issue templates): testing with project and status item"
  .github/ISSUE_TEMPLATE/42AI_issue.md
  .github/workflows/issue_triage.yaml
Labels: invalid

#70 doc(github page): update index/readme
  docs/_layouts/default.html
  docs/index.md
Labels: documentation

#71 64 doc milstone make readme great again description
  README.md
Labels: documentation

#80 doc(github page): preliminary viz
  docs/index.md
  docs/jadot_pie.png
  docs/lepen_pie.png
  docs/macron_pie.png
  docs/melenchon_pie.png
  docs/pecresse_pie.png
  docs/zemmour_pie.png
Labels: documentation

#83 75 feat data script to request tweets from twitter api
  .42AI/get_dataset_script1.sh
  src/__main__.py
  src/data/main.py
Labels: feature
